### ISSUE TITLE
Needs something pinging it

### ISSUE THREAD

**Issue by nateberkopec** [TechAtNYU/inwork#6]
need to prevent dyno spindown

new relic
pingdom

**Comment by revivek** [comment]
Can we build another Heroku app that pings the other Heroku app?

On Mon, Feb 11, 2013 at 8:29 AM, Nate Berkopec notifications@github.comwrote:

> need to prevent dyno spindown
> 
> new relic
> pingdom
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TechAtNYU/inwork/issues/6..

## 

_Vivek Patel_
914.356.0778 · 1.vivekpatel@gmail.com · @revivekhttp://www.twitter.com/revivek

**Comment by nateberkopec** [comment]
new relic and pingdom will both do this, why make it so complicated?

you could conceivably use heroku scheduler to ping it

**Comment by revivek** [comment]
Ah, my bad, I didn't understand. I'll set one up today.

On Mon, Feb 11, 2013 at 12:08 PM, Nate Berkopec notifications@github.comwrote:

> new relic and pingdom will both do this, why make it so complicated?
> 
> you could conceivably use heroku scheduler to ping it
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TechAtNYU/inwork/issues/6#issuecomment-13390489.

## 

_Vivek Patel_
914.356.0778 · 1.vivekpatel@gmail.com · @revivekhttp://www.twitter.com/revivek
